#
# Executes commands at the start of an interactive session.
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# Source local variables
hostname=`hostname -s`
if ! [ "${hostname#C02QR144FVH8}" = "${hostname}" ]; then
  if [[ -a $HOME/.workprofile ]]
  then
      source $HOME/.workprofile
  fi
fi

if ! [ "${hostname#Chriss-MacBook-Pro}" = "${hostname}" ]; then
  if [[ -a $HOME/.homeprofile ]]
  then
      source $HOME/.homeprofile
  fi
fi


# Customize to your needs    ---------------------------------
# ------------------------------------------------------------
# this is an addendum that adds things from dotfiles
# use the csturtevant/dotfiles project from github
export ZSH=$HOME/.zprezto

# Source config variables
if [[ -a $ZSH/zsh/config.zsh ]]
then
    source $ZSH/zsh/config.zsh
fi

# your project folder that we can `c [tab]` to
export PROJECTS=~/Code

# all of our zsh files
typeset -U config_files
config_files=($ZSH/*/*.zsh) # changed from ($ZSH/**/*.zsh) to exclude modules

# load the path files
for file in ${(M)config_files:#*/*path.zsh}
do
  source $file
done

# # # I have commented out the below item as it seems unnecessary 
# # # as these files are already accessible via path
# # load everything but the path and completion files
# for file in ${${config_files:#*/path.zsh}:#*/completion.zsh}
# do
#   source $file
# done

unset config_files

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# Java Home 
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
# export PATH="$PATH:$JAVA_HOME/bin"

# # Ensure user-installed binaries take precedence
export PATH=~/.bin:$PATH
# # Ensure that scripts folder in git repo is added to the path.
export PATH=~/notes/Sync/scripts:$PATH
# # Load Jersey / JAX-RS
export PATH=~/Documents/Programs/jaxrs-ri:$PATH
# # Load Apache Tomcat
export PATH=~/Documents/Programs/apache-tomcat-8.0.32:$PATH
# Make sure /usr/local/bin is a part of the path
export PATH=/usr/local/bin:$PATH
# Make sure yarn is a part of the path
export PATH="$HOME/.yarn/bin:$PATH"

# # Load .bashrc if it exists
# # test -f ~/.bashrc && source ~/.bashrc
# # Designate Editor
# # export EDITOR="/Applications/Emacs.app/Contents/MacOS/Emacs"
# export ALTERNATE_EDITOR=""
export EDITOR=emacsclient

# export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
# export PATH="$PATH:$JAVA_HOME/bin"

# # # Default Maven Opts
 export MAVEN_OPTS="-Xmx1g -Xms1g -XX:MaxPermSize=1g"

# # Maven Opts for large repository
# export MAVEN_OPTS="-Xmx1g -XX:MaxPermSize=1024m -Duser.language=en -Duser.country=us -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=4001,server=y,suspend=n"
# # export MAVEN_OPTS="-Xmx1g -XX:MaxPermSize=1024m -Duser.language=en -Duser.country=us -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=4001,server=y,suspend=y"

# # export MAVEN_OPTS='-Xmx1g -XX:MaxPermSize=1024 -Duser.language=en -Duser.country=us -Xnoagent -Djava.compiler=NONE'
# set vim as the default git editor // used with git config --global core.editor "vim"
# export GIT_EDITOR=vim
# # List of sources
# source ~/.bin/git-prompt.sh
# # source ~/.bin/gpush.sh

# # zstyle ':completion:*:*:git:*' script ~/.zsh/.git-completion.zsh
# # fpath=(~/.zsh $fpath)

# # List of global aliases
alias -g pa=" | ag " # pipe to ag (pa)
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
# # List of aliases
alias chrome='open -a "Google Chrome" '
alias copypath='pwd|pbcopy'
alias fn="find . -print | ag "
alias ga="git add"
alias gh="cd ~/gitHub"
alias gw="git-wtf"
alias l="ls -Gla"
alias ls="ls -G"
alias ll="ls -Gla"
alias mc="mvn clean install"
alias mcnt="mvn clean install -DskipTests"
alias mt="mvn test"
alias pd="popd" # pop the directory off of the stack

# Spacemacs
alias sm="/usr/local/Cellar/emacs-mac/emacs-25.2-z-mac-6.3/bin/emacsclient -nc "
alias smg="open -a /usr/local/Cellar/emacs-mac/emacs-25.2-z-mac-6.3/Emacs.app "
alias smdmn="emacs --daemon"
alias killsmdmn="emacsclient -e '(client-save-kill-emacs)'"

# Fasd
alias fsm="f -e emacsclient "

# # Configurations
# # Fzf - Fuzzy File Finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# # # Pyenv
# if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
# if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
# nvm use 0.12.7
# # # # # Run naven wuth the given options
# # mvnd () {
# #         export MAVEN_OPTS='-Xmx1g -Duser.language=en -Duser.country=us -Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=4000,server=y,suspend=n'
# #         mvn "$@";
# #         export MAVEN_OPTS='-Xmx1g -Duser.language=en -Duser.country=us -Xnoagent -Djava.compiler=NONE'
# # }

# # The next line updates PATH for the Google Cloud SDK.
# # if [ -f /Users/csturtevant/Downloads/google-cloud-sdk/path.bash.inc ]; then
# #   source '/Users/csturtevant/Downloads/google-cloud-sdk/path.bash.inc'
# # fi

# # # The next line enables shell command completion for gcloud.
# # if [ -f /Users/csturtevant/Downloads/google-cloud-sdk/completion.bash.inc ]; then
# #   source '/Users/csturtevant/Downloads/google-cloud-sdk/completion.bash.inc'
# # fi

[ -f ~/.lc2/bin/.lc2-init.sh ] && source ~/.lc2/bin/.lc2-init.sh

# test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
