cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'
tap 'railwaycat/emacsmacport'
tap 'beeftornado/rmtree'

brew 'the_silver_searcher'
brew 'coreutils'
brew 'emacs-mac'
brew 'fasd'
brew 'fzf'
brew 'nave'
brew 'python'
brew 'python3'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'tmux'
brew 'unrar'
brew 'wget'
brew 'yarn'

cask 'java'
cask 'vlc'
