cask_args appdir: '/Applications'

tap 'beeftornado/rmtree'
tap 'caskroom/cask'
tap 'clangen/musikcube'
tap 'homebrew/bundle'
tap 'puma/puma'
tap 'railwaycat/emacsmacport'

brew 'the_silver_searcher'
brew 'coreutils'
brew 'docker'
brew 'emacs-mac'
brew 'fasd'
brew 'fzf'
brew 'git'
brew 'go'
brew 'httpie'
brew 'musikcube'
brew 'mysql'
brew 'nave'
brew 'nmap'
brew 'node'
brew 'python'
brew 'python3'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'tldr'
brew 'tmux'
brew 'unrar'
brew 'wget'
brew 'yarn'

cask 'alfred'
cask 'bartender'
cask 'dash'
cask 'easyfind'
cask 'iterm2'
cask 'java'
cask 'jetbrains-toolbox'
cask 'rescuetime'
cask 'spectacle'
cask 'spotify'
cask 'visual-studio-code'
cask 'vlc'
